// Generated by gencpp from file server/AgentTrajectory.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_AGENTTRAJECTORY_H
#define SERVER_MESSAGE_AGENTTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace server
{
template <class ContainerAllocator>
struct AgentTrajectory_
{
  typedef AgentTrajectory_<ContainerAllocator> Type;

  AgentTrajectory_()
    : trajetory()  {
    }
  AgentTrajectory_(const ContainerAllocator& _alloc)
    : trajetory(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _trajetory_type;
  _trajetory_type trajetory;





  typedef boost::shared_ptr< ::server::AgentTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server::AgentTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct AgentTrajectory_

typedef ::server::AgentTrajectory_<std::allocator<void> > AgentTrajectory;

typedef boost::shared_ptr< ::server::AgentTrajectory > AgentTrajectoryPtr;
typedef boost::shared_ptr< ::server::AgentTrajectory const> AgentTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server::AgentTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server::AgentTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server::AgentTrajectory_<ContainerAllocator1> & lhs, const ::server::AgentTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.trajetory == rhs.trajetory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server::AgentTrajectory_<ContainerAllocator1> & lhs, const ::server::AgentTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server::AgentTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::AgentTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AgentTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AgentTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AgentTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AgentTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server::AgentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03de543be07dd3938d8e0d46d2eeada0";
  }

  static const char* value(const ::server::AgentTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03de543be07dd393ULL;
  static const uint64_t static_value2 = 0x8d8e0d46d2eeada0ULL;
};

template<class ContainerAllocator>
struct DataType< ::server::AgentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server/AgentTrajectory";
  }

  static const char* value(const ::server::AgentTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server::AgentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3[] trajetory\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::server::AgentTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server::AgentTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajetory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server::AgentTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server::AgentTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "trajetory[]" << std::endl;
    for (size_t i = 0; i < v.trajetory.size(); ++i)
    {
      s << indent << "  trajetory[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.trajetory[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_MESSAGE_AGENTTRAJECTORY_H
