// Generated by gencpp from file server/AgentTrajectories.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_AGENTTRAJECTORIES_H
#define SERVER_MESSAGE_AGENTTRAJECTORIES_H

#include <ros/service_traits.h>


#include <server/AgentTrajectoriesRequest.h>
#include <server/AgentTrajectoriesResponse.h>


namespace server
{

struct AgentTrajectories
{

typedef AgentTrajectoriesRequest Request;
typedef AgentTrajectoriesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AgentTrajectories
} // namespace server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server::AgentTrajectories > {
  static const char* value()
  {
    return "85c557dfbba925aa1e8e38fb4786f127";
  }

  static const char* value(const ::server::AgentTrajectories&) { return value(); }
};

template<>
struct DataType< ::server::AgentTrajectories > {
  static const char* value()
  {
    return "server/AgentTrajectories";
  }

  static const char* value(const ::server::AgentTrajectories&) { return value(); }
};


// service_traits::MD5Sum< ::server::AgentTrajectoriesRequest> should match
// service_traits::MD5Sum< ::server::AgentTrajectories >
template<>
struct MD5Sum< ::server::AgentTrajectoriesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server::AgentTrajectories >::value();
  }
  static const char* value(const ::server::AgentTrajectoriesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::AgentTrajectoriesRequest> should match
// service_traits::DataType< ::server::AgentTrajectories >
template<>
struct DataType< ::server::AgentTrajectoriesRequest>
{
  static const char* value()
  {
    return DataType< ::server::AgentTrajectories >::value();
  }
  static const char* value(const ::server::AgentTrajectoriesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server::AgentTrajectoriesResponse> should match
// service_traits::MD5Sum< ::server::AgentTrajectories >
template<>
struct MD5Sum< ::server::AgentTrajectoriesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server::AgentTrajectories >::value();
  }
  static const char* value(const ::server::AgentTrajectoriesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::AgentTrajectoriesResponse> should match
// service_traits::DataType< ::server::AgentTrajectories >
template<>
struct DataType< ::server::AgentTrajectoriesResponse>
{
  static const char* value()
  {
    return DataType< ::server::AgentTrajectories >::value();
  }
  static const char* value(const ::server::AgentTrajectoriesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_MESSAGE_AGENTTRAJECTORIES_H
