// Generated by gencpp from file server/AgentTrajectoriesResponse.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_AGENTTRAJECTORIESRESPONSE_H
#define SERVER_MESSAGE_AGENTTRAJECTORIESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server
{
template <class ContainerAllocator>
struct AgentTrajectoriesResponse_
{
  typedef AgentTrajectoriesResponse_<ContainerAllocator> Type;

  AgentTrajectoriesResponse_()
    : radii()  {
    }
  AgentTrajectoriesResponse_(const ContainerAllocator& _alloc)
    : radii(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _radii_type;
  _radii_type radii;





  typedef boost::shared_ptr< ::server::AgentTrajectoriesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server::AgentTrajectoriesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AgentTrajectoriesResponse_

typedef ::server::AgentTrajectoriesResponse_<std::allocator<void> > AgentTrajectoriesResponse;

typedef boost::shared_ptr< ::server::AgentTrajectoriesResponse > AgentTrajectoriesResponsePtr;
typedef boost::shared_ptr< ::server::AgentTrajectoriesResponse const> AgentTrajectoriesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server::AgentTrajectoriesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server::AgentTrajectoriesResponse_<ContainerAllocator1> & lhs, const ::server::AgentTrajectoriesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.radii == rhs.radii;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server::AgentTrajectoriesResponse_<ContainerAllocator1> & lhs, const ::server::AgentTrajectoriesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::AgentTrajectoriesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AgentTrajectoriesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AgentTrajectoriesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86da10d5fb2d7c814d1c23728386d2d6";
  }

  static const char* value(const ::server::AgentTrajectoriesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86da10d5fb2d7c81ULL;
  static const uint64_t static_value2 = 0x4d1c23728386d2d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server/AgentTrajectoriesResponse";
  }

  static const char* value(const ::server::AgentTrajectoriesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] radii\n"
;
  }

  static const char* value(const ::server::AgentTrajectoriesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radii);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentTrajectoriesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server::AgentTrajectoriesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server::AgentTrajectoriesResponse_<ContainerAllocator>& v)
  {
    s << indent << "radii[]" << std::endl;
    for (size_t i = 0; i < v.radii.size(); ++i)
    {
      s << indent << "  radii[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.radii[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_MESSAGE_AGENTTRAJECTORIESRESPONSE_H
